books/urls.py
from django.urls import path
from . import views

app_name = 'books'
urlpatterns = [
    # books
    path('', views.BooksModelView.as_view(), name='index'),

    # books/book/
    path('book/', views.BookList.as_view(), name='book_list'),

    # books/author/
    path('author/', views.AuthorList.as_view(), name='author_list'),

    # books/publisher/
    path('publisher/', views.PublisherList.as_view(), name='publisher_list'),

    # books/book/99/
    path('book/<int:pk>', views.BookDetail.as_view(), name='book_detail'),

    # books/author/99/
    path('author/<int:pk>', views.AuthorDetail.as_view(), name='author_detail'),

    # books/publisher/99/
    path('publisher/<int:pk>', views.PublisherDetail.as_view(), name='publisher_detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('polls/', include('polls.urls')),
    path('books/', include('books.urls')),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    
    # 클래스 뷰로 변경하기 위한 url로 변경 
    # path('', views.index, name='index'),
    # path('<int:question_id>/', views.detail, name='detail'),
    # path('<int:question_id>/results/', views.results, name='results'),
    # path('<int:question_id>/vote/', views.vote, name='vote'),

    # 테이블의 특정 레코드를 조회하는 경우 Primary Key로 검색을 하는데,
    # Primary Key를 담을 변수명을 pk라고 사용하기 때문에 pk로 변경함
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

books/models.py
from django.db import models

class Book(models.Model):
    title = models.CharField(max_length=100)
    # N:N
    authors = models.ManyToManyField('Author') 
    # N:1
    # ForeignKey를 사용시 on_delete option은 필수
    publisher = models.ForeignKey('Publisher', on_delete=models.CASCADE) 
    publication_date = models.DateField()

    def __str__(self):
        return self.title

class Author(models.Model):
    name = models.CharField(max_length=50)
    salutation = models.CharField(max_length=100)
    email = models.EmailField()
    

    def __str__(self):
        return self.name

class Publisher(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    website = models.URLField()

    def __str__(self):
        return self.name

polls/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

books/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic import ListView, DetailView
from books.models import Book, Author, Publisher

class BooksModelView(TemplateView):
    # 필수적으로 template_name을 넣어서 사용
    template_name = 'books/index.html'

    # TemplateView경우 넘겨줄 컨텍스트 변수가 있는 경우 get_context_data() 메소드를 오버라이딩해서 정의해준다.
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['model_list'] = ['Book', 'Author', 'Publisher']
        return context

class BookList(ListView):
    model = Book

class AuthorList(ListView):
    model = Author

class PublisherList(ListView):
    model = Publisher

class BookDetail(DetailView):
    model = Book

class AuthorDetail(DetailView):
    model = Author

class PublisherDetail(DetailView):
    model = Publisher

mysite/views.py
from django.views.generic.base import TemplateView
from django.apps import apps

class HomeView(TemplateView):

    template_name = 'home.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['app_list'] = ['polls', 'books']
        dictVerbose = {}
        # apps.get_app_configs[] 메소드를 호출하면, 
        # settings.py 파일의 INSTALLED_APPS에 등록된 각 앱의 설정 클래스들을 담은 리스트를 반환
        for app in apps.get_app_configs():
            # site-packages 문자열이 들어있으면 외부 라이브러리 앱을 의미하므로 제외
            if 'site-packages' not in app.path:
                print('lavel: ' + app.label)
                print('verbose_name: ' + app.verbose_name)
                dictVerbose[app.label] = app.verbose_name
                
        context['verbose_dict'] = dictVerbose
        return context

polls/views.py
from django.http import HttpResponseRedirect, HttpResponse

# from django.core.urlresolvers import reverse
# 변경되었음
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from polls.models import Choice, Question
from django.views import generic
import logging

logger = logging.getLogger(__name__)

# 클래스 뷰로 변경
# def index(request):
#     latest_question_list = Question.objects.all().order_by('-pub_date')[:5]
#     return render(request, 'polls/index.html', {'latest_qustion_list': latest_question_list})


# ListView를 상속받는 경우는 객체가 들어있는 리스트를 구성해서 이를 컨텍스트 변수로 템플릿 시스템에 넘겨주면 됩니다.
# 만일 이런 리스트를 테이블에 들어있는 모든 레코드를 가져와 구성하는 경우에는 테이블명, 즉 모델 클래스명만 지정해주면 됩니다.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'lastest_question_list'
    def get_queryset(self):
        # 최근 생성된 질문 5개를 반환함
        return Question.objects.order_by('-pub_date')[:5]
    
# 클래스 뷰로 변경
# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})


# DetailView를 상속받는 경우는 특정 객체 하나를 컨텍스트 변수에 담아서 템플릿 시스템에 넘겨주면 됩니다.
# 만일 특정 객체를 데이블에서 Primary Key로 조회해서 가져오는 경우에는 테이블명, 즉 모델 클래스명만 지정해주면 됩니다.
class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

def vote(request, question_id):
    # __name__은 모듈 경로를 담고 있는 파이썬 내장 변수
    # polls.views
    logger.debug("vote().question_id: %s" % question_id)
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_mesage': "You didn't select a choice."
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

# 클래스 뷰로 변경
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

books/templates/books/author_detail.html
{% extends "base_books.html" %}

{% block content %}
    <h1>{{ object.name }}</h1>
    <p>{{ object.salutation }}</p>
    <li>email: {{ object.email }}</li>
{% endblock %}

books/templates/books/author_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Books List</h2>
    <ul>
        {% for author in object_list %}
            <li><a href="{% url 'books:author_detail' author.id %}">{{ author.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

books/templates/books/book_detail.html
{% extends "base_books.html" %}

{% block content %}
    <h1>{{ object.title }}</h1>
    <br>
    <li>Author:
        {% for author in object.author.all %}
            {{ author }}
            {% if not forloop.last %},{% else %}{% endif %}
        {% endfor %}
    </li>
    <li>Publisher:{{ object.publisher }}</li>
    <li>Publication date: {{ object.publication_date }}</li>
{% endblock %}

books/templates/books/book_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Books List</h2>
    <ul>
        {% for book in object_list %}
            <li><a href="{% url 'books:book_detail' book.id %}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

books/templates/books/index.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Books Management System</h2>
    <ul>
        {% for modelname in model_list %}
            {% with "books:"|add:modelname|lower|add:"_list" as urlvar %}
                <li><a href="{% url urlvar %}">{{ modelname }}</a></li>
            {% endwith %}
        {% endfor %}
    </ul>
{% endblock %}

books/templates/books/publisher_detail.html
{% extends "base_books.html" %}

{% block content %}
    <h1>{{ object.name }}</h1>
    <p>{{ object.website }}</p>
    <li>Address: {{ object.address }}</li>
{% endblock %}

books/templates/books/publisher_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Books List</h2>
    <ul>
        {% for publisher in object_list %}
            <li><a href="{% url 'books:publisher_detail' publisher.id %}">{{ publisher.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

polls/templates/polls/detail.html
{% extends "base_polls.html" %}

{% block content %}

<h1> {{ question.question_text }} </h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
        {% endfor %}
        <input type="submit" value="Vote"/>
    </form>

{% endblock content %}

polls/templates/polls/index.html
{% extends "base_polls.html" %}


{% block content %}
    <h2>Polls Question List</h2>
    {% if latest_qustion_list %}
        <ul>
            {% for question in latest_qustion_list %}
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock content %}



    

polls/templates/polls/results.html
{% extends "base_polls.html" %}

{% block content %}

    <h1> {{ question.question_text }} </h1>

    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again</a>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'admin/css/base.css' %}" />
    <title>{% block title %}My Amazing Site{% endblock %}</title>
</head>

<body>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/">Project_Home</a></li>
            <li><a href="/admin/">Admin</a></li>
        </ul>
        {% endblock %}
        <br>
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/base_books.html
{% extends "base.html" %}

{% block title %}Books Application Site{% endblock %}

{% block sidebar %}
{{ block.super }}
<ul>
    <li><a href="/books/">Books_Home</a></li>
</ul>
{% endblock %}

templates/base_polls.html
{% extends "base.html" %}

<title>{% block title %} Polls Application Site{% endblock %}</title>

{% block sidebar %}
{{ block.super}}

<ul>
    <li><a href="/polls/">Polls_Home</a></li>
</ul>

{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block content %}
    <h2>yogae Django Application</h2>
    <ul>
        {% comment %} {% for appname in app_list %}
            {% with appname|add:":"|add:"index" as urlvar%}
                <li><a href="{% url urlvar %}">{{ appname }}</a></li>
            {% endwith %}
        {% endfor %} {% endcomment %}

        {% comment %} verbose_dict를 순회 {% endcomment %}
        {% comment %} 템플릿 문법에서는 함수 호출을 의미하는 ()를 사용하지 않음 {% endcomment %}
        {% for key, value in verbose_dict.items %}
            <li><a href="{% url key|add:':index' %}">{{ value }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}